[build]
builder = "nixpacks"
buildCommand = "mvn clean package -DskipTests"

[deploy]
startCommand = "java -Dserver.address=0.0.0.0 -jar target/participatehere-backend-1.0.0.jar"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
